# Generated by Django 4.2.26 on 2025-11-13 15:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre del color')),
            ],
            options={
                'verbose_name_plural': 'Tipo de color',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre de insumo')),
            ],
            options={
                'verbose_name_plural': 'Tipo de insumo',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Tipo de unidad a medir')),
            ],
            options={
                'verbose_name_plural': 'Unidad de medicion',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoja_vida', ckeditor.fields.RichTextField(blank=True, default='')),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedores')),
                ('tipo_color', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insumo.tipo_color')),
                ('tipo_insumo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insumo.tipo_insumo')),
            ],
            options={
                'verbose_name_plural': 'Insumos',
            },
        ),
    ]
