# Generated by Django 4.2.26 on 2025-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('dni', models.CharField(max_length=20, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=128, verbose_name='Mail')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuario', verbose_name='Imagen')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('contacto', models.CharField(max_length=50, verbose_name='Telefono de contacto')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es miembro del staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superusuario')),
                ('sector_asignado', models.ManyToManyField(blank=True, to='sector.nombre_sector')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
