# Generated by Django 4.2.26 on 2025-11-13 15:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre contacto')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono contacto')),
            ],
            options={
                'verbose_name_plural': 'Contacto Cliente',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit_o_cuil', models.CharField(max_length=50, unique=True, verbose_name='CUIT / CUIL')),
                ('razon_social', models.CharField(max_length=50, unique=True, verbose_name='Razon social')),
                ('fantasia', models.CharField(max_length=50, verbose_name='Nombre fantasia')),
                ('mail', models.EmailField(blank=True, max_length=128, verbose_name='Mail')),
                ('direccion', models.CharField(blank=True, max_length=50, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Telefono')),
                ('imagen', models.ImageField(blank=True, default='', upload_to='cliente', verbose_name='Imagen')),
                ('hoja_vida', ckeditor.fields.RichTextField(blank=True, default='')),
                ('contacto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.contacto_cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
