# Generated by Django 4.2.26 on 2025-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nombre_Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre del sector')),
            ],
            options={
                'verbose_name_plural': 'Nombre del sector',
            },
        ),
    ]
