# Generated by Django 4.2.26 on 2025-11-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NombrePrototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre de Prototipo')),
            ],
            options={
                'verbose_name_plural': 'Nombre de Prototipo',
            },
        ),
        migrations.CreateModel(
            name='PiezaPrototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='Ancho')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='Alto')),
                ('metros', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='Metros')),
                ('nombreprototipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prototipo.nombreprototipo')),
            ],
            options={
                'verbose_name_plural': 'Piezas de prototipo con unidad de medida',
            },
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Pieza')),
            ],
            options={
                'verbose_name_plural': 'Nombre de Pieza',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('0', 'contables'), ('1', 'cortables'), ('2', 'medibles')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre asignado')),
                ('imagen', models.ImageField(blank=True, default='', upload_to='prototipo', verbose_name='Imagen')),
                ('prototipo_armado', models.ManyToManyField(to='prototipo.piezaprototipo')),
            ],
            options={
                'verbose_name_plural': 'Prototipo',
            },
        ),
        migrations.AddField(
            model_name='piezaprototipo',
            name='piezas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prototipo.piezas'),
        ),
        migrations.AddField(
            model_name='piezaprototipo',
            name='tipo_pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototipo.tipo_pieza'),
        ),
    ]
