# Generated by Django 4.2.26 on 2025-11-13 15:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('prototipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Activo'), ('1', 'Finalizado'), ('2', 'Cancelado'), ('3', 'En espera'), ('4', 'Pausado')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, unique=True, verbose_name='Codigo')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('fecha_ingreso', models.DateTimeField(blank=True, verbose_name='Fecha Inicio')),
                ('fecha_egreso', models.DateTimeField(blank=True, verbose_name='Fecha Entrega')),
                ('imagen_general', models.ImageField(upload_to='ficha_tecnica', verbose_name='Imagen general')),
                ('hoja_vida_general', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones generales')),
                ('imagen_corte', models.ImageField(blank=True, default='', upload_to='corte', verbose_name='Imagen corte')),
                ('hoja_vida_corte', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones corte')),
                ('imagen_avios', models.ImageField(blank=True, default='', upload_to='avios', verbose_name='Imagen avios')),
                ('hoja_vida_avios', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones avios')),
                ('imagen_estampado', models.ImageField(blank=True, default='', upload_to='estampado', verbose_name='Imagen estampado')),
                ('hoja_vida_estampado', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones estampado')),
                ('imagen_confeccion', models.ImageField(blank=True, default='', upload_to='confeccion', verbose_name='Imagen confeccion')),
                ('hoja_vida_confeccion', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones confeccion')),
                ('hoja_vida_calidad', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones control de calidad')),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('estado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ficha_tecnica.estado')),
                ('prototipo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prototipo.prototipo')),
            ],
            options={
                'verbose_name_plural': 'Ficha Tecnica',
            },
        ),
    ]
